---
title: "Introduction"
teaching: 0
exercises: 0
questions:
- "Key question (FIXME)"
objectives:
- "First learning objective. (FIXME)"
keypoints:
- "First key point. Brief Answer to questions. (FIXME)"
---

## Why should we even care?

Data is not just numbers. Data can also be text. 
It can range from a column in 
a spread sheet where some observation is coded by a word, that we need to 
read, normalise and count. To the complete Ulysses by James Joyce, where it might
be of interest that the word "old" has been used 490 times. And that the frequency
increases rather dramatically in the last ~2000 sentences of the novel.

```{r old_in_ulysses, echo= F}
library(gutenbergr)
my_mirror <- "http://mirrors.xmission.com/gutenberg/"

gutenberg_download(4300, mirror = my_mirror) %>% 
  pull(text) %>% 
  tokenizers::tokenize_sentences() %>% 
  unlist() %>% 
  as_tibble() %>% 
  mutate(sentences = row_number()) %>% 
  mutate(gammel = str_detect(value, " old ")) %>% 
  mutate(count = cumsum(gammel)) %>% 
  ggplot(aes(sentences, count, group=1)) +
  geom_point()  +
  ggtitle('Cumulative count of the word "old" over sentences',
          subtitle = 'in "Ulysses" by James Joyce')
```

So we would like to be able to manipulate text in R. 

Or rather, we would like to be able to manipulate strings. Text implies that 
this is something that we can read and understand (given that we know the 
language). But in this context, strings can also be *B184465*, or 
*TATTCTGGGAATAGTGCCTATCTCTGCCTATTTGTCTGGTTGTTCAATTCAGGCACGTAG*, six random 
digits preceeded by a "B", and part of the human genome respectively.

We want to be able to detect if the word "fawning" even occurs in "Ulysses"
(it does - once, at the end of a sentence, immediately after the word "bearish").

We want to be able to count how many times a given pattern of characters
appears in a text, whether it is "old", or "Two adenines, followed by either
one guanine or one cytosine, followed by at least three Thymines".

We want to be able to replace all instances of "old" with "young" in order to
give new and perhaps confusing meaning to "Ulysses". And we want to be able 
to analyse which words most commonly occurs immediately before and after "old".

And we want to be able to generate the title of the plot above, replacing the
word "old" automatically depending on what we actually count.

All of this, and more, will be covered in this course. We can only scratch at 
the surface of this subject, but hopefully you will have a better understanding 
of what can be done, and how, with strings in R.

{% include links.md %}

